# Generated by Django 5.1.1 on 2024-11-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriaproducto',
            fields=[
                ('idcategoriaproducto', models.IntegerField(db_column='idCategoriaProducto', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'categoriaproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.IntegerField(db_column='idCliente', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecliente',
            fields=[
                ('iddetallecliente', models.IntegerField(db_column='idDetalleCliente', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=2)),
                ('ocupacion', models.IntegerField()),
                ('edad', models.CharField(max_length=45)),
                ('estadocivil', models.IntegerField(db_column='estadoCivil')),
                ('categoriaciudad', models.CharField(db_column='categoriaCiudad', max_length=3)),
                ('estadia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'detallecliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.IntegerField(db_column='idFactura', primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturacategoriaproducto',
            fields=[
                ('idfactura', models.IntegerField(db_column='idFactura', primary_key=True, serialize=False)),
                ('idcategoriaproducto', models.IntegerField(db_column='idCategoriaProducto')),
                ('cantidadproducto', models.IntegerField(blank=True, db_column='cantidadProducto', null=True)),
            ],
            options={
                'db_table': 'facturacategoriaproducto',
                'managed': False,
            },
        ),
    ]
