# Generated by Django 5.1.1 on 2024-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayorista9', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturacionResumida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('genero', models.CharField(blank=True, max_length=2, null=True)),
                ('ocupacion', models.IntegerField(blank=True, null=True)),
                ('estadocivil', models.IntegerField(blank=True, db_column='estadoCivil', null=True)),
                ('categoriaciudad', models.CharField(blank=True, db_column='categoriaCiudad', max_length=2, null=True)),
                ('estadia', models.CharField(blank=True, max_length=10, null=True)),
                ('idcategoriaproducto', models.IntegerField(db_column='idCategoriaProducto')),
                ('suma', models.DecimalField(blank=True, decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'facturacion_resumida',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Detallecliente',
        ),
    ]
